#!/usr/bin/env python3
"""Generate a low-fidelity Rex blockout GLB without Blender.

This is an art handoff/source placeholder. The Unity runtime placeholder is
generated by FitGameRexAssetScaffolder because this project does not currently
include a native glTF importer package.
"""

import json
import struct
from pathlib import Path


OUT = Path(__file__).with_name("rex_lowfi_blockout.glb")


def align4(data: bytes) -> bytes:
    return data + (b"\x00" * ((4 - len(data) % 4) % 4))


def pack_floats(values):
    return struct.pack("<" + "f" * len(values), *values)


def pack_ushorts(values):
    return struct.pack("<" + "H" * len(values), *values)


def main():
    # Cube uses face-unique vertices so flat shaded viewers have correct normals.
    positions = [
        -0.5, -0.5, -0.5, 0.5, -0.5, -0.5, 0.5, 0.5, -0.5, -0.5, 0.5, -0.5,
        -0.5, -0.5, 0.5, -0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, -0.5, 0.5,
        -0.5, -0.5, -0.5, -0.5, 0.5, -0.5, -0.5, 0.5, 0.5, -0.5, -0.5, 0.5,
        0.5, -0.5, -0.5, 0.5, -0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, -0.5,
        -0.5, 0.5, -0.5, 0.5, 0.5, -0.5, 0.5, 0.5, 0.5, -0.5, 0.5, 0.5,
        -0.5, -0.5, -0.5, -0.5, -0.5, 0.5, 0.5, -0.5, 0.5, 0.5, -0.5, -0.5,
    ]
    normals = [
        0, 0, -1, 0, 0, -1, 0, 0, -1, 0, 0, -1,
        0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
        -1, 0, 0, -1, 0, 0, -1, 0, 0, -1, 0, 0,
        1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
        0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
        0, -1, 0, 0, -1, 0, 0, -1, 0, 0, -1, 0,
    ]
    indices = [
        0, 1, 2, 0, 2, 3,
        4, 5, 6, 4, 6, 7,
        8, 9, 10, 8, 10, 11,
        12, 13, 14, 12, 14, 15,
        16, 17, 18, 16, 18, 19,
        20, 21, 22, 20, 22, 23,
    ]

    chunks = []
    views = []

    def add_buffer_view(blob: bytes, target: int) -> int:
        offset = sum(len(chunk) for chunk in chunks)
        padded = align4(blob)
        chunks.append(padded)
        views.append({"buffer": 0, "byteOffset": offset, "byteLength": len(blob), "target": target})
        return len(views) - 1

    pos_view = add_buffer_view(pack_floats(positions), 34962)
    normal_view = add_buffer_view(pack_floats(normals), 34962)
    index_view = add_buffer_view(pack_ushorts(indices), 34963)
    binary = b"".join(chunks)

    materials = [
        ("skin", [0.93, 0.66, 0.48, 1.0]),
        ("hair_black", [0.03, 0.035, 0.04, 1.0]),
        ("outfit_black", [0.055, 0.07, 0.08, 1.0]),
        ("leggings_black", [0.025, 0.03, 0.035, 1.0]),
        ("shoes_black", [0.08, 0.085, 0.09, 1.0]),
        ("sole_light", [0.82, 0.86, 0.86, 1.0]),
        ("accent_teal", [0.13, 0.83, 0.65, 1.0]),
        ("eye", [0.08, 0.12, 0.14, 1.0]),
    ]

    node_specs = [
        ("Body", [0, 1.12, 0], [0.72, 1.16, 0.46], 2),
        ("Hood", [0, 1.56, 0.13], [0.62, 0.28, 0.2], 2),
        ("Shorts", [0, 0.69, 0], [0.64, 0.28, 0.32], 2),
        ("Head", [0, 1.87, -0.02], [0.52, 0.56, 0.46], 0),
        ("HairTop", [0, 2.12, -0.03], [0.48, 0.16, 0.42], 1),
        ("HairFront_L", [-0.12, 2.03, -0.25], [0.17, 0.18, 0.13], 1),
        ("HairFront_R", [0.14, 2.02, -0.25], [0.17, 0.17, 0.13], 1),
        ("Eye_L", [-0.11, 1.9, -0.31], [0.06, 0.06, 0.025], 7),
        ("Eye_R", [0.11, 1.9, -0.31], [0.06, 0.06, 0.025], 7),
        ("LeftArm", [-0.47, 1.15, 0], [0.18, 0.68, 0.18], 0),
        ("RightArm", [0.47, 1.15, 0], [0.18, 0.68, 0.18], 0),
        ("WristBand_L", [-0.47, 0.8, -0.01], [0.19, 0.07, 0.16], 6),
        ("WristBand_R", [0.47, 0.8, -0.01], [0.19, 0.07, 0.16], 6),
        ("LeftLegging", [-0.2, 0.24, 0], [0.2, 0.78, 0.2], 3),
        ("RightLegging", [0.2, 0.24, 0], [0.2, 0.78, 0.2], 3),
        ("LeftLegStripe", [-0.27, 0.28, -0.12], [0.035, 0.5, 0.025], 6),
        ("RightLegStripe", [0.27, 0.28, -0.12], [0.035, 0.5, 0.025], 6),
        ("LeftShoe", [-0.2, -0.25, -0.05], [0.28, 0.14, 0.42], 4),
        ("RightShoe", [0.2, -0.25, -0.05], [0.28, 0.14, 0.42], 4),
        ("LeftSole", [-0.2, -0.33, -0.05], [0.3, 0.055, 0.44], 5),
        ("RightSole", [0.2, -0.33, -0.05], [0.3, 0.055, 0.44], 5),
        ("Zipper", [0, 1.18, -0.285], [0.035, 0.72, 0.025], 6),
        ("ChestMark", [0.17, 1.35, -0.295], [0.15, 0.07, 0.025], 6),
    ]

    gltf = {
        "asset": {"version": "2.0", "generator": "FitGame Rex lowfi blockout generator"},
        "scene": 0,
        "scenes": [{"nodes": list(range(len(node_specs)))}],
        "nodes": [
            {"name": name, "mesh": i, "translation": translation, "scale": scale}
            for i, (name, translation, scale, _mat) in enumerate(node_specs)
        ],
        "meshes": [
            {
                "name": name,
                "primitives": [{
                    "attributes": {"POSITION": 0, "NORMAL": 1},
                    "indices": 2,
                    "material": material,
                }],
            }
            for name, _translation, _scale, material in node_specs
        ],
        "materials": [
            {"name": name, "pbrMetallicRoughness": {"baseColorFactor": color, "metallicFactor": 0, "roughnessFactor": 0.55}}
            for name, color in materials
        ],
        "accessors": [
            {"bufferView": pos_view, "componentType": 5126, "count": 24, "type": "VEC3", "min": [-0.5, -0.5, -0.5], "max": [0.5, 0.5, 0.5]},
            {"bufferView": normal_view, "componentType": 5126, "count": 24, "type": "VEC3"},
            {"bufferView": index_view, "componentType": 5123, "count": len(indices), "type": "SCALAR"},
        ],
        "bufferViews": views,
        "buffers": [{"byteLength": len(binary)}],
    }

    json_blob = align4(json.dumps(gltf, separators=(",", ":")).encode("utf-8"))
    bin_blob = align4(binary)
    total_len = 12 + 8 + len(json_blob) + 8 + len(bin_blob)
    with OUT.open("wb") as f:
        f.write(struct.pack("<III", 0x46546C67, 2, total_len))
        f.write(struct.pack("<I4s", len(json_blob), b"JSON"))
        f.write(json_blob)
        f.write(struct.pack("<I4s", len(bin_blob), b"BIN\x00"))
        f.write(bin_blob)
    print(OUT)


if __name__ == "__main__":
    main()
