CREATE TABLE exercises (
    id VARCHAR(64) PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    animation_key VARCHAR(128) NOT NULL,
    duration_seconds INTEGER NOT NULL,
    default_sets INTEGER NOT NULL,
    default_reps INTEGER NOT NULL,
    instruction VARCHAR(512) NOT NULL,
    strength_impact INTEGER NOT NULL,
    endurance_impact INTEGER NOT NULL,
    core_impact INTEGER NOT NULL,
    flexibility_impact INTEGER NOT NULL,
    fat_burn_impact INTEGER NOT NULL,
    recovery_impact INTEGER NOT NULL,
    sort_order INTEGER NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE workout_sessions (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id),
    avatar_id UUID NOT NULL REFERENCES avatars(id),
    status VARCHAR(32) NOT NULL,
    started_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    duration_seconds INTEGER,
    xp_gained INTEGER,
    client_request_id VARCHAR(128),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_workout_sessions_user_status
    ON workout_sessions(user_id, status);

INSERT INTO exercises (
    id,
    name,
    animation_key,
    duration_seconds,
    default_sets,
    default_reps,
    instruction,
    strength_impact,
    endurance_impact,
    core_impact,
    flexibility_impact,
    fat_burn_impact,
    recovery_impact,
    sort_order,
    status,
    created_at,
    updated_at
) VALUES
(
    'squat_basic',
    '深蹲',
    'workout_squat',
    45,
    2,
    12,
    '脚跟稳定，膝盖跟随脚尖方向，下蹲后主动站起。',
    2,
    1,
    1,
    0,
    1,
    0,
    10,
    'active',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'jumping_jack_basic',
    '开合跳',
    'workout_jumping_jack',
    40,
    2,
    20,
    '保持轻快节奏，落地时膝盖微屈，呼吸不要憋住。',
    0,
    2,
    0,
    0,
    2,
    0,
    20,
    'active',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'plank_basic',
    '平板支撑',
    'workout_plank',
    35,
    1,
    1,
    '收紧核心，肩、髋、脚跟保持在一条直线上。',
    0,
    1,
    2,
    0,
    0,
    0,
    30,
    'active',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'stretch_basic',
    '拉伸',
    'workout_stretch',
    35,
    1,
    1,
    '放慢动作，保持呼吸，感受大腿后侧和髋部放松。',
    0,
    0,
    0,
    2,
    0,
    1,
    40,
    'active',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);
